# Generated by Django 2.0.5 on 2018-06-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
