# Generated by Django 2.0.5 on 2018-06-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_response_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='result',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
